server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    example: example.t

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.vd.event.consumer: INFO

vd:
  kafka:
    listener:
      sleep-period: ${KAFKA_SLEEP_LISTENER_PERIOD:10000}
      restart-period: ${KAFKA_RESTART_LISTENER_PERIOD:120000}